# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: client_command.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x63lient_command.proto\"\x88\x03\n\rClientCommand\x12\x12\n\ncommand_id\x18\x01 \x01(\x03\x12\x0f\n\x07user_id\x18\x02 \x01(\x03\x12$\n\x0cwaitlist_add\x18\x03 \x01(\x0b\x32\x0c.WaitlistAddH\x00\x12&\n\rwaitlist_move\x18\x04 \x01(\x0b\x32\r.WaitlistMoveH\x00\x12*\n\x0fwaitlist_delete\x18\x05 \x01(\x0b\x32\x0f.WaitlistDeleteH\x00\x12\x15\n\x04play\x18\x06 \x01(\x0b\x32\x05.PlayH\x00\x12\x17\n\x05pause\x18\x07 \x01(\x0b\x32\x06.PauseH\x00\x12&\n\radjust_volume\x18\x08 \x01(\x0b\x32\r.AdjustVolumeH\x00\x12$\n\x0cget_waitlist\x18\t \x01(\x0b\x32\x0c.GetWaitlistH\x00\x12$\n\x0cget_mlibrary\x18\n \x01(\x0b\x32\x0c.GetMLibraryH\x00\x12)\n\x0fget_active_song\x18\x0b \x01(\x0b\x32\x0e.GetActiveSongH\x00\x42\t\n\x07\x63ommand\"\x1a\n\x0bWaitlistAdd\x12\x0b\n\x03sid\x18\x01 \x01(\x03\"+\n\x0cWaitlistMove\x12\x0b\n\x03wid\x18\x01 \x01(\x03\x12\x0e\n\x06offset\x18\x02 \x01(\x03\"\x1d\n\x0eWaitlistDelete\x12\x0b\n\x03wid\x18\x01 \x01(\x03\"\'\n\x04Play\x12\x0b\n\x03sid\x18\x01 \x01(\x03\x12\x12\n\ntime_stamp\x18\x02 \x01(\x03\"\x15\n\x05Pause\x12\x0c\n\x04time\x18\x01 \x01(\x03\"\x1e\n\x0c\x41\x64justVolume\x12\x0e\n\x06volume\x18\x01 \x01(\x03\"\r\n\x0bGetWaitlist\"\x1b\n\x0bGetMLibrary\x12\x0c\n\x04page\x18\x01 \x01(\x03\"\x0f\n\rGetActiveSongb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'client_command_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CLIENTCOMMAND._serialized_start=25
  _CLIENTCOMMAND._serialized_end=417
  _WAITLISTADD._serialized_start=419
  _WAITLISTADD._serialized_end=445
  _WAITLISTMOVE._serialized_start=447
  _WAITLISTMOVE._serialized_end=490
  _WAITLISTDELETE._serialized_start=492
  _WAITLISTDELETE._serialized_end=521
  _PLAY._serialized_start=523
  _PLAY._serialized_end=562
  _PAUSE._serialized_start=564
  _PAUSE._serialized_end=585
  _ADJUSTVOLUME._serialized_start=587
  _ADJUSTVOLUME._serialized_end=617
  _GETWAITLIST._serialized_start=619
  _GETWAITLIST._serialized_end=632
  _GETMLIBRARY._serialized_start=634
  _GETMLIBRARY._serialized_end=661
  _GETACTIVESONG._serialized_start=663
  _GETACTIVESONG._serialized_end=678
# @@protoc_insertion_point(module_scope)
